# Generated by Django 6.0.2 on 2026-03-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID (G-XXXXX)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gsc_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Google Search Console Verification'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gtm_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Tag Manager ID (GTM-XXXXX)'),
        ),
    ]
