# Generated by Django 6.0.2 on 2026-03-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_ga_id_sitesettings_gsc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='compliance_ccpa',
            field=models.BooleanField(default=False, verbose_name='CCPA (California)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compliance_gdpr',
            field=models.BooleanField(default=False, verbose_name='GDPR (Unión Europea)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compliance_hipaa',
            field=models.BooleanField(default=False, verbose_name='HIPAA (EE.UU. Salud)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compliance_lgpd',
            field=models.BooleanField(default=False, verbose_name='LGPD (Brasil)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_banner_description',
            field=models.TextField(blank=True, default='Este sitio utiliza cookies para mejorar tu experiencia. Puedes personalizar tus preferencias o aceptar todas las cookies.', verbose_name='Descripción del banner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_banner_title',
            field=models.CharField(blank=True, default='Utilizamos cookies', max_length=200, verbose_name='Título del banner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar banner de consentimiento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_policy_url',
            field=models.URLField(blank=True, verbose_name='URL Política de Cookies'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookies_analytics_enabled',
            field=models.BooleanField(default=True, verbose_name='Cookies de Analítica'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookies_functional_enabled',
            field=models.BooleanField(default=True, verbose_name='Cookies Funcionales'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookies_marketing_enabled',
            field=models.BooleanField(default=False, verbose_name='Cookies de Marketing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, verbose_name='URL Política de Privacidad'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service_url',
            field=models.URLField(blank=True, verbose_name='URL Términos de Servicio'),
        ),
    ]
