# Generated by Django 6.0 on 2026-01-21 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('book_available', 'Libro Disponible'), ('loan_expiring', 'Préstamo por Vencer'), ('new_review', 'Nueva Reseña'), ('subscription_expiring', 'Suscripción por Vencer'), ('admin_announcement', 'Anuncio Administrativo'), ('welcome', 'Bienvenida'), ('book_recommendation', 'Recomendación de Libro')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('link', models.URLField(blank=True, help_text='URL opcional para redirigir al usuario', null=True, verbose_name='Enlace')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_emailed', models.BooleanField(default=False, help_text='Indica si se envió notificación por correo', verbose_name='Enviada por Email')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales relacionados con la notificación', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
            },
        ),
    ]
