# Generated by Django 6.0.2 on 2026-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('book_available', 'Libro Disponible'), ('loan_expiring', 'Préstamo por Vencer'), ('new_review', 'Nueva Reseña'), ('subscription_expiring', 'Suscripción por Vencer'), ('admin_announcement', 'Anuncio Administrativo'), ('welcome', 'Bienvenida'), ('book_recommendation', 'Recomendación de Libro'), ('community_activity', 'Actividad en Club'), ('trial_expiring', 'Trial por Vencer')], max_length=30, verbose_name='Tipo'),
        ),
    ]
