# Generated by Django 6.0 on 2025-12-31 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_review_reviewhelpful_favorite_readinghistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Progress percentage based on current_page / total_pages', max_digits=5)),
                ('zoom_level', models.DecimalField(decimal_places=2, default=1.0, help_text="User's preferred zoom level (1.00 = 100%)", max_digits=3)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('total_reading_time', models.IntegerField(default=0, help_text='Total reading time in seconds')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='content.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Session',
                'verbose_name_plural': 'Reading Sessions',
                'db_table': 'readings',
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', '-last_read_at'], name='readings_user_id_81b133_idx'), models.Index(fields=['book', '-last_read_at'], name='readings_book_id_449daf_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
