# Generated by Django 6.0 on 2026-01-03 00:32

import apps.content.models
import apps.content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_reading_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG, WebP, GIF. Tamaño máximo: 5MB', null=True, upload_to=apps.content.models.author_photo_upload_path, validators=[apps.content.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG, WebP, GIF. Tamaño máximo: 5MB', null=True, upload_to=apps.content.models.book_cover_upload_path, validators=[apps.content.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, help_text='Formato: PDF. Tamaño máximo: 50MB', null=True, upload_to=apps.content.models.book_file_upload_path, validators=[apps.content.validators.validate_pdf_file]),
        ),
    ]
