# Generated by Django 6.0 on 2026-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_author_photo_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='author_name_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', '-created_at'], name='book_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', '-created_at'], name='book_auth_created_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_premium', '-created_at'], name='book_prem_created_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='book_created_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='book_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='book_title_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='category_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_idx'),
        ),
    ]
