# Generated by Django 6.0.1 on 2026-01-11 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_query_optimization_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('selected_text', models.TextField()),
                ('color', models.CharField(choices=[('yellow', 'Amarillo'), ('green', 'Verde'), ('blue', 'Azul'), ('pink', 'Rosa'), ('purple', 'Púrpura')], default='yellow', max_length=20)),
                ('position_data', models.JSONField(default=dict, help_text='JSON with coordinates and selection info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='content.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('selected_text', models.TextField(blank=True, default='')),
                ('position_data', models.JSONField(default=dict, help_text='JSON with coordinates and selection info')),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='content.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('highlight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='content.highlight')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page_number', '-created_at'],
                'indexes': [models.Index(fields=['user', 'book'], name='content_boo_user_id_49bf90_idx'), models.Index(fields=['created_at'], name='content_boo_created_84035e_idx')],
                'unique_together': {('user', 'book', 'page_number')},
            },
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'book'], name='content_hig_user_id_e73308_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['page_number'], name='content_hig_page_nu_9dd3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['created_at'], name='content_hig_created_fc246c_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['user', 'book'], name='content_ann_user_id_5ca013_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['page_number'], name='content_ann_page_nu_1f9228_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['created_at'], name='content_ann_created_4d19df_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['is_private'], name='content_ann_is_priv_31c1e1_idx'),
        ),
    ]
