# Generated by Django 6.0.1 on 2026-01-12 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_highlight_annotation_bookmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='book_isbn_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book', '-rating', '-created_at'], name='review_book_rating_idx'),
        ),
    ]
