# Generated by Django 6.0 on 2026-02-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_book_doab_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
