# Generated by Django 6.0 on 2026-03-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_book_language_book_published_year_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Fecha de disponibilidad. Null = disponible inmediatamente.', null=True),
        ),
    ]
