# Generated by Django 6.0 on 2026-01-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('employee', 'Funcionário'), ('teacher', 'Professor'), ('librarian', 'Bibliotecário'), ('moderator', 'Moderador'), ('content_manager', 'Gestor de Conteúdo'), ('other', 'Outro')], default='student', max_length=20),
        ),
    ]
