# Generated by Django 6.0.1 on 2026-02-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_days', models.IntegerField(default=90, help_text='Número de días antes de que la contraseña expire', verbose_name='Días de expiración')),
                ('is_enabled', models.BooleanField(default=False, help_text='Habilitar o deshabilitar la política de expiración', verbose_name='Política habilitada')),
                ('min_length', models.IntegerField(default=8, verbose_name='Longitud mínima')),
                ('require_uppercase', models.BooleanField(default=True, verbose_name='Requiere mayúsculas')),
                ('require_lowercase', models.BooleanField(default=True, verbose_name='Requiere minúsculas')),
                ('require_numbers', models.BooleanField(default=True, verbose_name='Requiere números')),
                ('require_special', models.BooleanField(default=False, verbose_name='Requiere caracteres especiales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política de Contraseñas',
                'verbose_name_plural': 'Políticas de Contraseñas',
                'db_table': 'password_policy',
            },
        ),
    ]
