# Generated by Django 6.0.2 on 2026-02-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_force_password_change_user_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('employee', 'Funcionário'), ('teacher', 'Professor'), ('librarian', 'Bibliotecário'), ('moderator', 'Moderador'), ('content_manager', 'Gestor de Conteúdo'), ('admin', 'Administrador'), ('other', 'Outro')], default='student', max_length=20),
        ),
    ]
