# Generated by Django 6.0.1 on 2026-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del período de prueba'),
        ),
    ]
