# Generated by Django 6.0.2 on 2026-02-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, help_text='e.g. 18-24, 25-34', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
