# Generated by Django 6.0 on 2026-01-21 01:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0009_perf_002_query_optimization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.PositiveIntegerField(help_text='Ejemplo: Copia 1 de 3', verbose_name='Número de Copia')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo')], default='good', max_length=10, verbose_name='Condición')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el estado o ubicación del ejemplar', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='content.book', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Ejemplar de Libro',
                'verbose_name_plural': 'Ejemplares de Libros',
                'db_table': 'book_copies',
                'ordering': ['book', 'copy_number'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido')], default='active', max_length=10, verbose_name='Estado')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('renewals_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Renovaciones')),
                ('max_renewals', models.PositiveIntegerField(default=2, verbose_name='Renovaciones Máximas')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto de Multa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='content.book', verbose_name='Libro')),
                ('book_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.bookcopy', verbose_name='Ejemplar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'loans',
                'ordering': ['-borrowed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Posición en Cola')),
                ('notified', models.BooleanField(default=False, help_text='Si el usuario fue notificado de disponibilidad', verbose_name='Notificado')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha límite para tomar el préstamo después de notificación', null=True, verbose_name='Expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_queue', to='content.book', verbose_name='Libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cola de Préstamo',
                'verbose_name_plural': 'Colas de Préstamos',
                'db_table': 'loan_queue',
                'ordering': ['book', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['book', 'is_available'], name='book_copies_book_id_2bd9bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcopy',
            unique_together={('book', 'copy_number')},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loans_user_id_efac20_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['book', 'status'], name='loans_book_id_6360b6_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'due_date'], name='loans_status_ca3b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanqueue',
            index=models.Index(fields=['book', 'notified'], name='loan_queue_book_id_804299_idx'),
        ),
        migrations.AddIndex(
            model_name='loanqueue',
            index=models.Index(fields=['user', 'created_at'], name='loan_queue_user_id_1ab5e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanqueue',
            unique_together={('user', 'book')},
        ),
    ]
