# Generated by Django 6.0 on 2026-03-04 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_book_available_from'),
        ('institutions', '0002_institutionmembership'),
        ('payments', '0004_transaction_payment_reference_and_more'),
        ('subscriptions', '0002_plan_plan_type_institutionsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('basic', 'Básica'), ('standard', 'Estándar'), ('premium', 'Premium'), ('specialized', 'Especializada')], default='basic', help_text='Nivel mínimo de plan requerido para acceso vía suscripción.', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('institutional_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio à la carte para instituciones.', max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio à la carte para usuarios individuales.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.AddField(
            model_name='institutionsubscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='Fin del período de gracia post-vencimiento.', null=True),
        ),
        migrations.AddField(
            model_name='institutionsubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Suscripción de prueba institucional.'),
        ),
        migrations.AddField(
            model_name='institutionsubscription',
            name='seats_used',
            field=models.IntegerField(default=0, help_text='Asientos actualmente ocupados (actualizado por signal).'),
        ),
        migrations.AddField(
            model_name='plan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio anual (si aplica).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('one_time', 'Pago único')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='free_trial_days',
            field=models.IntegerField(default=0, help_text='Días de prueba gratuitos al activar.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='grace_period_days',
            field=models.IntegerField(default=3, help_text='Días de gracia post-vencimiento.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_concurrent_sessions',
            field=models.IntegerField(default=3, help_text='Sesiones de lectura simultáneas permitidas.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=1, help_text='Máximo de usuarios (para planes institucionales). 0 = ilimitado.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('standard', 'Estándar'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', help_text='Nivel de acceso que otorga este plan.', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='Fin del período de gracia post-vencimiento.', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID para renovaciones automáticas.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio mensual o precio base.', max_digits=10),
        ),
        migrations.CreateModel(
            name='CollectionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.book')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.collection')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('collection', 'book')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='collections', through='subscriptions.CollectionBook', to='content.book'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, help_text='Máximo de usos. Null = ilimitado.', null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Planes aplicables. Vacío = todos.', to='subscriptions.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='subscriptions.coupon')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionCollectionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_access', to='subscriptions.collection')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_access', to='institutions.institution')),
                ('subscription', models.ForeignKey(blank=True, help_text='Suscripción que otorgó este acceso. Null = compra à la carte.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.institutionsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.collection')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Colecciones explícitas de este plan. Vacío = acceso por tier.', related_name='plans', through='subscriptions.PlanCollection', to='subscriptions.collection'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['tier', 'is_active'], name='coll_tier_active_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='coll_slug_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institutioncollectionaccess',
            unique_together={('institution', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='plancollection',
            unique_together={('plan', 'collection')},
        ),
    ]
