# Generated by Django 6.0 on 2026-03-04 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_book_available_from'),
        ('payments', '0004_transaction_payment_reference_and_more'),
        ('subscriptions', '0003_collection_institutionsubscription_grace_period_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('permanent', 'Permanente'), ('rental', 'Alquiler')], default='permanent', max_length=10)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Null = acceso permanente. Con fecha = alquiler temporal.', null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='content.book')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'valid_until'], name='bkpurchase_user_valid_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
