# Generated by Django 6.0.2 on 2026-03-02 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('honeypot_field_name', models.CharField(default='website_url', help_text='Name of the hidden honeypot field', max_length=100)),
                ('captcha_provider', models.CharField(choices=[('none', 'Ninguno (solo honeypot)'), ('turnstile', 'Cloudflare Turnstile'), ('recaptcha_v3', 'Google reCAPTCHA v3'), ('numeric', 'CAPTCHA numérico'), ('time_based', 'Validación por tiempo')], default='none', max_length=20)),
                ('captcha_site_key', models.CharField(blank=True, default='', help_text='Site key for Turnstile or reCAPTCHA', max_length=255)),
                ('captcha_secret_key', models.CharField(blank=True, default='', help_text='Secret key for Turnstile or reCAPTCHA (server-side only)', max_length=255)),
                ('captcha_min_seconds', models.PositiveIntegerField(default=3, help_text='Minimum seconds before submission is accepted (time_based)')),
                ('captcha_score_threshold', models.FloatField(default=0.5, help_text='Minimum score for reCAPTCHA v3 (0.0–1.0)')),
                ('success_message', models.TextField(default='Formulario enviado exitosamente.', help_text='Message shown after successful submission')),
                ('redirect_url', models.URLField(blank=True, default='', help_text='Optional URL to redirect after submission')),
                ('version', models.PositiveIntegerField(default=1)),
                ('field_snapshots', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('email', 'Email'), ('textarea', 'Texto largo'), ('select', 'Selección'), ('checkbox', 'Casilla'), ('radio', 'Opción múltiple'), ('number', 'Número'), ('date', 'Fecha'), ('file', 'Archivo'), ('hidden', 'Oculto')], max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('default_value', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('form_version', models.PositiveIntegerField(help_text='Version of the form schema when submitted')),
                ('data', models.JSONField(default=dict)),
                ('file_uploads', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_spam', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='forms.form')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'unique_together': {('form', 'email')},
            },
        ),
    ]
