# Generated by Django 6.0.2 on 2026-02-21 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('template_key', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de correo',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('welcome', 'Bienvenida'), ('password_reset', 'Recuperación de contraseña'), ('notification', 'Notificación'), ('subscription', 'Suscripción')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de correo',
            },
        ),
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('from_email', models.EmailField(default='noreply@bvs.com', max_length=254)),
                ('from_name', models.CharField(blank=True, default='BVS', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SMTP',
            },
        ),
    ]
