# Generated by Django 6.0.2 on 2026-03-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('welcome', 'Bienvenida'), ('password_reset', 'Recuperación de contraseña'), ('notification', 'Notificación'), ('subscription', 'Suscripción'), ('form_submission', 'Envío de formulario')], max_length=50, unique=True),
        ),
    ]
