# Generated by Django 6.0.6 on 2026-06-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institutionmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Sigla o abreviatura de la institución (ej: ULA). Solo para visualización.', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, help_text='Código de país ISO 3166-1 alpha-2 (ej: AO, BR, PT, MZ).', max_length=2),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('UNI', 'Universidad'), ('IES', 'Institución de Educación Superior'), ('INV', 'Centro de Investigación'), ('ESC', 'Centro Escolar'), ('OTR', 'Otro')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='institution',
            name='ror_id',
            field=models.CharField(blank=True, help_text='Identificador ROR (Research Organization Registry). Solo el hash corto, ej: 02mhbdp94. Consultar https://ror.org para verificar.', max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(help_text='Identificador único estructurado generado automáticamente (ej: AO-UNI-0001). No cambiar una vez asignado.', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['country', 'institution_type'], name='inst_country_type_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['ror_id'], name='inst_ror_idx'),
        ),
    ]
