# Generated by Django 6.0 on 2026-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
