# Generated by Django 6.0.2 on 2026-02-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='User provided reference for manual transfers', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='PayPal Order ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('PIX', 'Pix'), ('SLIP', 'Bank Slip'), ('PAYPAL', 'PayPal'), ('MANUAL_TRANSFER', 'Manual Transfer')], default='CREDIT_CARD', max_length=20),
        ),
    ]
